[build]
  command = "DISABLE_ESLINT_PLUGIN=true npm run build && cd api && npm install && npm run build"
  publish = "build"
  functions = "api/dist"

[build.environment]
  REACT_APP_API_URL = "https://budget-gm-backend.onrender.com"
  NODE_VERSION = "18"
  NPM_VERSION = "9"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200 