[build]
  command = "npm run build"
  publish = "build"
  environment = { CI = "false" }

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  REACT_APP_API_URL = "https://budget-gm-backend.onrender.com" 