[build]
  command = "npm run build && cd api && npm install && npm run build"
  publish = "build"
  functions = "api/dist"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9" 